version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.Webapp
    image: paincave.azurecr.io/specialized_webapp:latest
    ports:
      - "8000:8000"
    volumes:
      - staticfiles:/app/staticfiles
    environment:
      POSTGRES_USER: specialized
      POSTGRES_DB: specialized_bikes
      POSTGRES_HOST: db  
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: amqp://specialized_celery_user:specialized!123@rabbitmq:5672/myvhost
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      POSTGRES_PASSWORD: mysecurepassword
      DEBUG: 0
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: Dockerfile.Database
    image: paincave.azurecr.io/specialized_database:latest
    environment:
      POSTGRES_USER: specialized
      POSTGRES_DB: specialized_bikes
      POSTGRES_PASSWORD: mysecurepassword
      POSTGRES_HOST: localhost 
      POSTGRES_PORT: 5432 
    healthcheck:
      test: pg_isready -h localhost -U specialized -d specialized_bikes
      interval: 30s
      timeout: 10s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.Rabbitmq
    image: paincave.azurecr.io/specialized_rabbit:latest
    environment:
      RABBITMQ_DEFAULT_USER: specialized_celery_user
      RABBITMQ_DEFAULT_PASS: specialized!123
      RABBITMQ_DEFAULT_VHOST: myvhost
    healthcheck:
      test: rabbitmqctl status
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  staticfiles:
  postgres_data:
