version: '3.8'  # Specify version if needed

services:
  webapp:
    build: 
      context: .
      dockerfile: Dockerfile.Webapp
    image: paincave.azurecr.io/specialized_webapp:latest  # Prefix with ACR
    ports:
      - "8000:8000"
    volumes:
      - staticfiles:/app/staticfiles
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: specialized
      POSTGRES_DB: specialized_bikes
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: amqp://specialized_celery_user:specialized!123@rabbitmq:5672/myvhost
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      POSTGRES_PASSWORD: mysecurepassword
    depends_on:
      - db
      - rabbitmq

  db: 
    build: 
      context: .
      dockerfile: Dockerfile.Database
    image: paincave.azurecr.io/specialized_database:latest  # Prefix with ACR
    environment:
      POSTGRES_USER: specialized
      POSTGRES_DB: specialized_bikes
      POSTGRES_PASSWORD: mysecurepassword
      POSTGRES_HOST: localhost 
      POSTGRES_PORT: 5432 

    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    build: 
      context: .
      dockerfile: Dockerfile.Rabbitmq
    image: paincave.azurecr.io/specialized_rabbit:latest  # Prefix with ACR
    environment:
      RABBITMQ_DEFAULT_USER: specialized_celery_user
      RABBITMQ_DEFAULT_PASS: specialized!123
      RABBITMQ_DEFAULT_VHOST: myvhost
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  staticfiles:
  postgres_data:
