services:
  webapp:
    build: 
      context: .
      dockerfile: Dockerfile.Webapp
    image: specialized_webapp:latest
    ports:
      - "8000:8000"
    volumes:
      - staticfiles:/app/staticfiles
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: specialized
      POSTGRES_DB: specialized_bikes
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: amqp://specialized_celery_user:specialized!123@rabbitmq:5672/myvhost
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      POSTGRES_PASSWORD: mysecurepassword
      DEBUG: 0
    depends_on:
      db:
        condition: service_healthy

  db: 
    build: 
      context: .
      dockerfile: Dockerfile.Database
    image: specialized_database:latest
    environment:
      POSTGRES_USER: specialized
      POSTGRES_DB: specialized_bikes
      POSTGRES_PASSWORD: mysecurepassword
      POSTGRES_HOST: localhost 
      POSTGRES_PORT: 5432 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U specialized -d specialized_bikes"]
      interval: 30s
      timeout: 10s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    build: 
      context: .
      dockerfile: Dockerfile.Rabbitmq
    image: specialized_rabbit:latest
    environment:
      RABBITMQ_DEFAULT_USER: specialized_celery_user
      RABBITMQ_DEFAULT_PASS: specialized!123
      RABBITMQ_DEFAULT_VHOST: myvhost
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  staticfiles:
  postgres_data: