# Generated by Django 5.1 on 2024-09-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutgoingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.TextField(default="")),
                ("method", models.CharField(default="", max_length=10)),
                ("response", models.TextField(default="")),
                ("payload", models.TextField(default="")),
                ("status_code", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
