# This sample corresponds to the result variable in parse_product_data (get_bikes.py)
sample_bike = {
    "__typename": "SearchProductResults",
    "archived": None,
    "defaultColorId": "271743-171305",
    "formattedPrice": None,
    "imageUrl": "https://assets.specialized.com/i/specialized/77420-02_SHIV-TT-SW-DISC-MODULE-TARBLK-WHT_HERO-SQUARE?$scom-plp-product-image-square$&fmt=auto",
    "intellisuggestData": "eJwcxDEKhTAMBuBcKPAn_V9D17Z5R3CXCiJu3n8QXL5l975ctqL1hz-jNmUklCOb9o6iSZpxwObsIhF0KBwmRikegs_zuY43AAD__4M2D-8",
    "intellisuggestSignature": "a1a6b05016e57bbdccd20c08bf3fb086dcbc8c6a5793575f94c5d8eb7470be33",
    "isBike": True,
    "modelYear": "2021",
    "msrp": 6000,
    "name": "S-Works Shiv TT Disc Module",
    "price": 6000,
    "primaryBadge": "",
    "productData": {
        "name": "S-Works Shiv TT Disc Module",
        "id": 171305,
        "brand": "Specialized",
        "price": "6000",
        "currencyCode": "USD",
        "position": "",
        "variant": "",
        "dimension1": "Framesets",
        "dimension2": "Road",
        "dimension3": "Shiv TT",
        "dimension4": "",
        "dimension5": "Performance",
        "dimension6": "S-Works",
        "dimension7": "",
        "dimension8": "male|female",
        "list": "Bikes|S-Works Bikes|Bikes|Road Bikes|Performance Road Bikes|Shiv TT",
    },
    "secondaryBadges": None,
    "subhead": None,
    "swatchesJSON": [
        {
            "onlinefrom": "",
            "id": "271743-171305",
            "thumbnail": "https://assets.specialized.com/i/specialized/77420-02_SHIV-TT-SW-DISC-MODULE-TARBLK-WHT_HERO-SQUARE?hybris-large",
            "swatch": "#000000::#ffffff",
            "color": "Gloss Tarmac Black/White",
            "colorFamily": "Black",
            "price": "6000",
            "is_exclusive": "False",
            "clearance": "False",
            "giftGuide": "False",
            "plpImageId": "https://assets.specialized.com/i/specialized/77420-02_SHIV-TT-SW-DISC-MODULE-TARBLK-WHT_HERO-SQUARE?$scom-plp-product-image-square$&fmt=auto",
            "colorOrder": "0",
            "colorLink": "s-works-shiv-tt-disc-module/p/171305",
            "prices": [
                {
                    "group": "consumer",
                    "minDiscountPrice": "",
                    "maxDiscountPrice": "",
                    "minPrice": "",
                    "maxPrice": "6000",
                    "minPriceminor": "",
                    "maxPriceminor": "600000",
                    "formattedMaxPrice": "$6,000.00",
                    "formattedMinPrice": None,
                }
            ],
            "available_quantity_color_level": "0",
            "instockrate": "0.000000",
        }
    ],
    "title": "S-Works Shiv TT Disc Module",
    "uid": "171305",
    "url": "/us/en/p/171305",
}
