name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker for the build process
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Azure using service principal credentials stored in the AZURE_CREDENTIALS secret
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to Azure Container Registry (ACR)
      - name: Log in to ACR
        run: az acr login --name paincave

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t paincave.azurecr.io/specialized:latest .

      # Push the Docker image to Azure Container Registry (ACR)
      - name: Push Docker image to ACR
        run: docker push paincave.azurecr.io/specialized:latest

  deploy:
    # The deploy job will only run after the build job completes successfully
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Log in to Azure using the service principal credentials stored in GitHub Secrets
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Restart the Azure Web App to apply the new container
      - name: Restart Web App
        run: az webapp restart --name paincave-webapp --resource-group paincave
