name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name paincave

      - name: Build Docker images
        run: docker compose -f docker-compose.yml build

      - name: Push Docker images to ACR
        run: docker compose -f docker-compose.yml push

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Web App
        run: |
          az webapp config container set --name paincave-webapp --resource-group paincave --multicontainer-config-type compose --multicontainer-config-file docker-compose.yml

      - name: Restart Web App
        run: az webapp restart --name paincave-webapp --resource-group paincave
